# Generated by Django 3.2.8 on 2021-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_seq', models.AutoField(db_column='COMMENT_SEQ', primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, db_column='COMMENT', max_length=2000, null=True)),
                ('reg_date', models.DateTimeField(blank=True, db_column='REG_DATE', null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('f_num', models.AutoField(db_column='F_NUM', primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, db_column='F_NAME', max_length=100, null=True)),
                ('f_area', models.FloatField(blank=True, db_column='F_AREA', null=True)),
            ],
            options={
                'db_table': 'crops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeepImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deepimages', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'farm_app_deepimages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deeplearnings',
            fields=[
                ('d_num', models.AutoField(db_column='D_NUM', primary_key=True, serialize=False)),
                ('d_comment', models.CharField(blank=True, db_column='D_COMMENT', max_length=200, null=True)),
                ('d_check', models.CharField(blank=True, db_column='D_CHECK', max_length=1, null=True)),
                ('d_date', models.DateTimeField(blank=True, db_column='D_DATE', null=True)),
                ('d_img1', models.CharField(blank=True, db_column='D_IMG1', max_length=200, null=True)),
                ('d_img2', models.CharField(blank=True, db_column='D_IMG2', max_length=200, null=True)),
                ('d_img3', models.CharField(blank=True, db_column='D_IMG3', max_length=200, null=True)),
            ],
            options={
                'db_table': 'deeplearnings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dronerunnings',
            fields=[
                ('dr_num', models.AutoField(db_column='DR_NUM', primary_key=True, serialize=False)),
                ('dr_date', models.DateTimeField(blank=True, db_column='DR_DATE', null=True)),
                ('ptc_name', models.CharField(blank=True, db_column='PTC_NAME', max_length=100, null=True)),
                ('dr_company', models.CharField(blank=True, db_column='DR_COMPANY', max_length=100, null=True)),
                ('dr_phone', models.CharField(blank=True, db_column='DR_PHONE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'dronerunnings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmdiaries',
            fields=[
                ('r_num', models.AutoField(db_column='R_NUM', primary_key=True, serialize=False)),
                ('r_plant', models.CharField(blank=True, db_column='R_PLANT', max_length=100, null=True)),
                ('r_bug', models.CharField(blank=True, db_column='R_BUG', max_length=100, null=True)),
                ('r_ftz', models.CharField(blank=True, db_column='R_FTZ', max_length=100, null=True)),
                ('r_low_c', models.FloatField(blank=True, db_column='R_LOW_C', null=True)),
                ('r_weather', models.CharField(blank=True, db_column='R_WEATHER', max_length=200, null=True)),
                ('r_date', models.DateTimeField(blank=True, db_column='R_DATE', null=True)),
                ('r_diary', models.CharField(blank=True, db_column='R_DIARY', max_length=2000, null=True)),
                ('r_pic1', models.CharField(blank=True, db_column='R_PIC1', max_length=200, null=True)),
                ('r_hum', models.FloatField(blank=True, db_column='R_HUM', null=True)),
                ('r_high_c', models.FloatField(blank=True, db_column='R_HIGH_C', null=True)),
                ('r_ptc_name', models.CharField(blank=True, db_column='R_PTC_NAME', max_length=100, null=True)),
                ('r_dr_memo', models.CharField(blank=True, db_column='R_DR_MEMO', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'farmdiaries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ImageField(blank=True, null=True, upload_to='historyimg/')),
            ],
            options={
                'db_table': 'farm_app_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'farm_app_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pestinfos',
            fields=[
                ('p_num', models.AutoField(db_column='P_NUM', primary_key=True, serialize=False)),
                ('p_bug', models.CharField(blank=True, db_column='P_BUG', max_length=100, null=True)),
                ('p_method', models.CharField(blank=True, db_column='P_METHOD', max_length=2000, null=True)),
                ('p_symtom', models.CharField(blank=True, db_column='P_SYMTOM', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'pestinfos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ptcinfos',
            fields=[
                ('ptc_num', models.AutoField(db_column='PTC_NUM', primary_key=True, serialize=False)),
                ('ptc_name', models.CharField(blank=True, db_column='PTC_NAME', max_length=100, null=True)),
                ('ptc_maker', models.CharField(blank=True, db_column='PTC_MAKER', max_length=100, null=True)),
                ('ptc_use', models.CharField(blank=True, db_column='PTC_USE', max_length=100, null=True)),
                ('ptc_quantity', models.FloatField(blank=True, db_column='PTC_QUANTITY', null=True)),
                ('ptc_pest', models.CharField(blank=True, db_column='PTC_PEST', max_length=100, null=True)),
                ('ptc_plant', models.CharField(blank=True, db_column='PTC_PLANT', max_length=100, null=True)),
                ('ptcimg', models.ImageField(blank=True, null=True, upload_to='ptcimage/')),
            ],
            options={
                'db_table': 'ptcinfos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(db_column='USER_ID', max_length=100, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(blank=True, db_column='USER_PWD', max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, db_column='USER_NAME', max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, db_column='USER_PHONE', max_length=20, null=True)),
                ('user_email', models.CharField(blank=True, db_column='USER_EMAIL', max_length=100, null=True)),
                ('user_addr', models.CharField(blank=True, db_column='USER_ADDR', max_length=200, null=True)),
                ('join_date', models.DateTimeField(blank=True, db_column='JOIN_DATE', null=True)),
                ('admin_yn', models.CharField(blank=True, db_column='ADMIN_YN', max_length=1, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
            ],
        ),
        migrations.CreateModel(
            name='OcrRsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocrresult', models.ImageField(blank=True, null=True, upload_to='ocrResult/')),
            ],
        ),
    ]
