# Generated by Django 3.2.8 on 2021-10-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='privent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_bug', models.CharField(blank=True, max_length=100, null=True)),
                ('pr_text', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
